# Generated by Django 5.1.1 on 2024-11-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_momo_alter_touch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touch',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
